### ISSUE TITLE
How do you patch axiom with this

### ISSUE THREAD

**Issue by Josh65-2201** [UpcraftLP/AxiomPatcher#1]
I can't run the file or drag and drop axiom on it or run it with Minecraft itself. How am I suppose to patch axiom with this?

**Comment by grim42** [comment]
Disclaimer: I'm not the dev

I got it to work on windows by opening the file using cmd.
I typed `java -jar AxiomPatcher-24.0519.1453.jar ` in the directory and it worked.

If you get an error message because the java version is too low, you need to find a high enough version (you probably have one on your PC, try searching for java.exe, or download one), try writing the full path to the java.exe, something like `C:\Users\YourName\.jdks\\your\path\to\your\exe\java.exe -jar AxiomPatcher-24.0519.1453.jar`

**Comment by Josh65-2201** [comment]
Thanks, I guess I was putting the axiom mod jar in since it works now.

**Comment by UpcraftLP** [comment]
Thank you for the report, I've released an update that now shows an error message if launched with the wrong Java version or if someone tries to run it as a Minecraft mod.
